# DB_HOST = "iot.cpe.ku.ac.th"
# DB_USER = "b6510545756"
# DB_PASSWD = "suparak.ar@ku.th"
# DB_NAME = "group09"

OPENAPI_STUB_DIR = "archive/stubold"
DB_HOST = "iot.cpe.ku.ac.th"
DB_USER = "b6510545322"
DB_PASSWD = "chayakarn.h@ku.th"
DB_NAME = "group09"