openapi: 3.0.0
info:
  title: PM2.5 Activity Decision API
  description:
    This API provides the PM2.5 data for the activity decision. 
    The data is collected from the questionnaire and the PM2.5 API.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8080/PMDecision
paths:
  /API:
    get:
      summary: Returns a list of API.
      operationId: controller.controller_get_api
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/API'
  /LocationtoDecision:
    get:
      summary: Returns a list of Decision.
      operationId: controller.controller_get_locationto_decision
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LocationtoDecision'
  /PMAPI:
    get:
      summary: Returns a list of PM.
      operationId: controller.controller_get_pm_api
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PMAPI'

components:
  schemas:
    API:
      type: object
      properties:
        id:
          type: integer
        ts:
          type: string
        district:
          type: string
        aqi:
          type: number
    LocationtoDecision:
      type: object
      properties:
        id:
          type: integer
        ts:
          type: string
        district:
          type: string
        AQI:
          type: number
        decision:
          type: string
    PMAPI:
      type: object
      properties:
        id:
          type: integer
        ts:
          type: string
        AQI:
          type: number