# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PMAPI(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, district: str=None, ts: str=None, aqi: float=None, pm25=None):  # noqa: E501
        """PMAPI - a model defined in Swagger

        :param district: The district of this PMAPI.  # noqa: E501
        :type district: str
        :param ts: The ts of this PMAPI.  # noqa: E501
        :type ts: str
        :param aqi: The aqi of this PMAPI.  # noqa: E501
        :type aqi: float
        :param pm2_5: The pm2_5 of this PMAPI.  # noqa: E501
        :type pm2_5: float
        """
        self.swagger_types = {
            'district': str,
            'ts': str,
            'aqi': float,
            'pm25': str
        }

        self.attribute_map = {
            'district': 'district',
            'ts': 'ts',
            'aqi': 'AQI',
            'pm2_5': 'PM2_5'
        }
        self._district = district
        self._ts = ts
        self._aqi = aqi
        self._pm25 = pm25

    @classmethod
    def from_dict(cls, dikt) -> 'PMAPI':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PMAPI of this PMAPI.  # noqa: E501
        :rtype: PMAPI
        """
        return util.deserialize_model(dikt, cls)

    @property
    def district(self) -> str:
        """Gets the district of this PMAPI.


        :return: The district of this PMAPI.
        :rtype: str
        """
        return self._district

    @district.setter
    def district(self, district: str):
        """Sets the district of this PMAPI.


        :param district: The district of this PMAPI.
        :type district: str
        """

        self._district = district

    @property
    def ts(self) -> str:
        """Gets the ts of this PMAPI.


        :return: The ts of this PMAPI.
        :rtype: str
        """
        return self._ts

    @ts.setter
    def ts(self, ts: str):
        """Sets the ts of this PMAPI.


        :param ts: The ts of this PMAPI.
        :type ts: str
        """

        self._ts = ts

    @property
    def aqi(self) -> float:
        """Gets the aqi of this PMAPI.


        :return: The aqi of this PMAPI.
        :rtype: float
        """
        return self._aqi

    @aqi.setter
    def aqi(self, aqi: float):
        """Sets the aqi of this PMAPI.


        :param aqi: The aqi of this PMAPI.
        :type aqi: float
        """

        self._aqi = aqi

    @property
    def pm25(self):
        """Gets the pm2_5 of this PMAPI.


        :return: The pm2_5 of this PMAPI.
        :rtype: float
        """
        return self._pm25

    @pm25.setter
    def pm25(self, pm25):
        """Sets the pm2_5 of this PMAPI.


        :param pm2_5: The pm2_5 of this PMAPI.
        :type pm2_5: float
        """

        self._pm2_5 = pm25
