# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PMAPI(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, ts: str=None, aqi: float=None):  # noqa: E501
        """PMAPI - a model defined in Swagger

        :param id: The id of this PMAPI.  # noqa: E501
        :type id: int
        :param ts: The ts of this PMAPI.  # noqa: E501
        :type ts: str
        :param aqi: The aqi of this PMAPI.  # noqa: E501
        :type aqi: float
        """
        self.swagger_types = {
            'id': int,
            'ts': str,
            'aqi': float
        }

        self.attribute_map = {
            'id': 'id',
            'ts': 'ts',
            'aqi': 'AQI'
        }
        self._id = id
        self._ts = ts
        self._aqi = aqi

    @classmethod
    def from_dict(cls, dikt) -> 'PMAPI':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PMAPI of this PMAPI.  # noqa: E501
        :rtype: PMAPI
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this PMAPI.


        :return: The id of this PMAPI.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this PMAPI.


        :param id: The id of this PMAPI.
        :type id: int
        """

        self._id = id

    @property
    def ts(self) -> str:
        """Gets the ts of this PMAPI.


        :return: The ts of this PMAPI.
        :rtype: str
        """
        return self._ts

    @ts.setter
    def ts(self, ts: str):
        """Sets the ts of this PMAPI.


        :param ts: The ts of this PMAPI.
        :type ts: str
        """

        self._ts = ts

    @property
    def aqi(self) -> float:
        """Gets the aqi of this PMAPI.


        :return: The aqi of this PMAPI.
        :rtype: float
        """
        return self._aqi

    @aqi.setter
    def aqi(self, aqi: float):
        """Sets the aqi of this PMAPI.


        :param aqi: The aqi of this PMAPI.
        :type aqi: float
        """

        self._aqi = aqi
